# Generated by Django 5.1 on 2024-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0002_doador_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='produto',
            field=models.CharField(default='Produto Não Especificado', max_length=255),
        ),
    ]
